# Generated by Django 3.2.3 on 2021-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (2, '删除')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=200, null=True, verbose_name='评论目标'),
        ),
    ]
